export const disciplineItem = [
  { label: "13th Octave LaHoChi", value: "13th-octave-lahochi" },
  { label: "Aboriginal Bush Medicine", value: "aboriginal-bush-medicine" },
  { label: "Access Bars Therapy", value: "access-bars-therapy" },
  { label: "Access Body Processes", value: "access-body-processes" },
  { label: "Acupuncture", value: "acupuncture" },
  { label: "Acupressure", value: "acupressure" },
  { label: "Akashic Records", value: "akashic-records" },
  { label: "Akashic Healing", value: "akashic-healing" },
  { label: "Animal Healing", value: "animal-healing" },
  { label: "Alexander Technique", value: "alexander-technique" },
  { label: "Alternative Medicine", value: "alternative-medicine" },
  { label: "Angelic Light", value: "angelic-light" },
  { label: "Aromatherapy", value: "aromatherapy" },
  { label: "Ayurveda", value: "ayurveda" },
  { label: "Biofield Healing", value: "biofield-healing" },
  { label: "Chakra Balancing", value: "chakra-balancing" },
  { label: "Crystal Healing", value: "crystal-healing" },
  { label: "Energy Medicine", value: "energy-medicine" },
  { label: "Herbal Medicine", value: "herbal-medicine" },
  { label: "Reiki Healing", value: "reiki-healing" },
];
