export const events = [
  {
    title: "Event title goes here",
    mode: "Offline",
    status: "Ongoing",
    description:
      "Lorem ipsum dolor sit amet consectetur. Lectus urna etiam imperdiet in amet sit tortor. Molestie quis mauris pellentesque.",
    location: "Event location goes here",
    link: null,
    dateTime: "10 Sep, 2025 at 05:00 PM - 09:00 PM",
    attendees: "153 / 300",
    price: "$15.00",
    thumbnail: "/img/event1.png",
    type: "live",
  },
  {
    title: "Event title goes here",
    mode: "Online",
    status: "Upcoming",
    description:
      "Lorem ipsum dolor sit amet consectetur. Lectus urna etiam imperdiet in amet sit tortor. Molestie quis mauris pellentesque.",
    location: null,
    link: "http://zoom21.43234df...",
    dateTime: "10 Sep, 2025 at 05:00 PM - 09:00 PM",
    attendees: "153 / 300",
    price: "$15.00",
    thumbnail: "/img/event2.png",
    type: "live",
  },
  {
    title: "Event title goes here",
    mode: "Offline",
    status: "Ongoing",
    description:
      "Lorem ipsum dolor sit amet consectetur. Lectus urna etiam imperdiet in amet sit tortor. Molestie quis mauris pellentesque.",
    location: "Event location goes here",
    link: null,
    dateTime: "10 Sep, 2025 at 05:00 PM - 09:00 PM",
    attendees: "153 / 300",
    price: "$15.00",
    thumbnail: "/img/event3.png",
    type: "live",
  },
  {
    title: "Event title goes here",
    mode: "On demand",
    status: "Upcoming",
    description:
      "Lorem ipsum dolor sit amet consectetur. Lectus urna etiam imperdiet in amet sit tortor. Molestie quis mauris pellentesque.",
    location: "Event location goes here",
    link: null,
    dateTime: "10 Sep, 2025 at 05:00 PM - 09:00 PM",
    attendees: "153 / 300",
    price: "$15.00",
    thumbnail: "/img/event4.png",
    type: "recorded",
  },
  {
    title: "Event title goes here",
    mode: "Offline",
    status: "Ongoing",
    description:
      "Lorem ipsum dolor sit amet consectetur. Lectus urna etiam imperdiet in amet sit tortor. Molestie quis mauris pellentesque.",
    location: "Event location goes here",
    link: null,
    dateTime: "10 Sep, 2025 at 05:00 PM - 09:00 PM",
    attendees: "153 / 300",
    price: "$15.00",
    thumbnail: "/img/event5.png",
    type: "live",
  },
  {
    title: "Event title goes here",
    mode: "On demand",
    status: "Upcoming",
    description:
      "Lorem ipsum dolor sit amet consectetur. Lectus urna etiam imperdiet in amet sit tortor. Molestie quis mauris pellentesque.",
    location: "Event location goes here",
    link: null,
    dateTime: "10 Sep, 2025 at 05:00 PM - 09:00 PM",
    attendees: "153 / 300",
    price: "$15.00",
    thumbnail: "/img/event6.png",
    type: "recorded",
  },
];
