export enum tagTypes {
  profile = "profile",
  notification = "notification",
  u_contact_us = "user_contact_us",
  a_terms = "a_terms",
  a_privacy = "a_privacy",
  a_fqa = "a_fqa",
  a_coupon = "a_coupon",
  a_newsletter = "a_newsletter",
  a_blog = "a_blog",
  a_single_blog = "a_single_blog",
  a_dashboard = "a_dashboard",
  a_users = "a_users",
  a_ticket = "a_ticket",
  a_podcast = "a_podcast",
  a_promotion = "a_promotion",
  a_slg_promotion = "a_slg_promotion",
  a_operator = "a_operator",
  a_slg_opertor = "a_slg_opertor",
  a_pricing = "a_pricing",
}

export const tagTypesList = [
  tagTypes.profile,
  tagTypes.notification,
  tagTypes.u_contact_us,
  tagTypes.a_terms,
  tagTypes.a_privacy,
  tagTypes.a_fqa,
  tagTypes.a_coupon,
  tagTypes.a_newsletter,
  tagTypes.a_blog,
  tagTypes.a_single_blog,
  tagTypes.a_dashboard,
  tagTypes.a_users,
  tagTypes.a_ticket,
  tagTypes.a_podcast,
  tagTypes.a_promotion,
  tagTypes.a_slg_promotion,
  tagTypes.a_operator,
  tagTypes.a_slg_opertor,
  tagTypes.a_pricing,
];
