import type { Metadata } from "next";
import { Montserrat } from "next/font/google"; // Importing Montserrat font
import "@/app/style/globals.css";
import Provider from "@/provider";

// Apply Montserrat font
const montserrat = Montserrat({
  variable: "--font-montserrat", // Font variable name
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Olistami",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth!">
      <body className={`${montserrat.variable}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
