import type { Metadata } from "next";
import { Montserrat } from "next/font/google"; // Importing Montserrat font
import "@/app/style/globals.css";

// Apply Montserrat font
const montserrat = Montserrat({
  variable: "--font-montserrat", // Font variable name
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Olistami",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`} // Applying the Montserrat font
      >
        {children}
      </body>
    </html>
  );
}
