import assets from "@/assets";
import { newsletSts } from "@/lib/constants";

export const featuresData = [
  {
    id: 1,
    key: "profile",
    icon: assets.feature.profile,
    bgColor: "#F7FAFF",
    shadow:
      "0 2px 4px 0 rgba(34, 117, 255, 0.25), 0 -2px 4px 0 rgba(34, 117, 255, 0.25), 2px 0 4px 0 rgba(34, 117, 255, 0.25), -2px 0 4px 0 rgba(34, 117, 255, 0.25)",
  },
  {
    id: 2,
    key: "discovery",
    icon: assets.feature.discovery,
    bgColor: "#FFF5F6",
    iconBgColor: "bg-pink-100",
    shadow:
      "0 2px 4px 0 rgba(255, 18, 56, 0.25), 0 -2px 4px 0 rgba(255, 18, 56, 0.25), 2px 0 4px 0 rgba(255, 18, 56, 0.25), -2px 0 4px 0 rgba(255, 18, 56, 0.25)",
  },
  {
    id: 3,
    key: "booking",
    icon: assets.feature.booking,
    bgColor: "#FDF6FF",
    shadow:
      " 0 2px 4px 0 rgba(204, 25, 255, 0.25), 0 -2px 4px 0 rgba(204, 25, 255, 0.25), 2px 0 4px 0 rgba(204, 25, 255, 0.25), -2px 0 4px 0 rgba(204, 25, 255, 0.25)",
  },
  {
    id: 4,
    key: "rating",
    icon: assets.feature.rating,
    bgColor: "#FFFDF1",
    shadow:
      "0 2px 4px 0 rgba(255, 221, 14, 0.25), 0 -2px 4px 0 rgba(255, 221, 14, 0.25), 2px 0 4px 0 rgba(255, 221, 14, 0.25), -2px 0 4px 0 rgba(255, 221, 14, 0.25)",
  },
  {
    id: 5,
    key: "payment",
    icon: assets.feature.payment,
    bgColor: "#F4FCFF",
    shadow:
      " 0 2px 4px 0 rgba(18, 190, 255, 0.25), 0 -2px 4px 0 rgba(18, 190, 255, 0.25), 2px 0 4px 0 rgba(18, 190, 255, 0.25), -2px 0 4px 0 rgba(18, 190, 255, 0.25)",
  },
  {
    id: 6,
    key: "subscription",
    icon: assets.feature.subscrit,
    bgColor: "#F9FFEE",
    shadow:
      " 0 2px 4px 0 rgba(171, 255, 16, 0.25), 0 -2px 4px 0 rgba(171, 255, 16, 0.25), 2px 0 4px 0 rgba(171, 255, 16, 0.25), -2px 0 4px 0 rgba(171, 255, 16, 0.25)",
  },
];

// export const disciplineOptions = [
//   { label: "Animal Healing", value: "Animal Healing" },
//   { label: "Animal Reiki", value: "Animal Reiki" },
//   { label: "Apitherapy", value: "Apitherapy" },
//   { label: "Aromatherapy", value: "Aromatherapy" },
//   { label: "Art Therapy", value: "Art Therapy" },
//   { label: "Acupressure", value: "Acupressure" },
//   { label: "Acupuncture", value: "Acupuncture" },
//   { label: "Akashic Healing", value: "Akashic Healing" },
//   { label: "Akashic Records", value: "Akashic Records" },
//   { label: "13th Octave LaHoChi", value: "13th Octave LaHoChi" },
//   { label: "Aboriginal Bush Medicine", value: "Aboriginal Bush Medicine" },
//   { label: "Access Bars Therapy", value: "Access Bars Therapy" },
//   { label: "Access Body Processes", value: "Access Body Processes" },
//   { label: "Alexander Technique", value: "Alexander Technique" },
//   { label: "Alternative Medicine", value: "Alternative Medicine" },
//   { label: "Angelic Light", value: "Angelic Light" },
//   { label: "Ashtanga Yoga", value: "Ashtanga Yoga" },
//   { label: "Assisted Stretching", value: "Assisted Stretching" },
//   { label: "Astrology", value: "Astrology" },
//   { label: "Attunement", value: "Attunement" },
//   { label: "Aura Healing", value: "Aura Healing" },
//   { label: "Auriculotherapy", value: "Auriculotherapy" },
//   { label: "Autogenic Training", value: "Autogenic Training" },
//   { label: "Autosuggestion", value: "Autosuggestion" },
//   { label: "Ayurveda", value: "Ayurveda" },
//   { label: "Bach Flower Therapy", value: "Bach Flower Therapy" },
//   { label: "Belief Code", value: "Belief Code" },
//   { label: "Bikram Yoga", value: "Bikram Yoga" },
//   { label: "Bilateral Stimulation", value: "Bilateral Stimulation" },
//   { label: "Binaural Beats", value: "Binaural Beats" },
//   { label: "Bio-Well", value: "Bio-Well" },
//   { label: "Bio-magnetic Therapy", value: "Bio-magnetic Therapy" },
//   {
//     label: "Biodynamic Craniosacral Therapy",
//     value: "Biodynamic Craniosacral Therapy",
//   },
//   { label: "Biofield Tuning", value: "Biofield Tuning" },
//   { label: "Biophoton Therapy", value: "Biophoton Therapy" },
//   { label: "Body Alignment", value: "Body Alignment" },
//   { label: "Body Code", value: "Body Code" },
//   { label: "Body Healing", value: "Body Healing" },
//   { label: "Bowen Therapy", value: "Bowen Therapy" },
//   { label: "Breathwork Therapy", value: "Breathwork Therapy" },
//   { label: "Brennan Healing Science", value: "Brennan Healing Science" },
//   { label: "Chair Yoga", value: "Chair Yoga" },
//   { label: "Chakra Healing", value: "Chakra Healing" },
//   { label: "Children Yoga", value: "Children Yoga" },
//   { label: "Chiropractic", value: "Chiropractic" },
//   { label: "Chromotherapy", value: "Chromotherapy" },
//   { label: "Chumpi Illumination", value: "Chumpi Illumination" },
//   { label: "Coaching", value: "Coaching" },
//   {
//     label: "Conscious Leadership Training",
//     value: "Conscious Leadership Training",
//   },
//   { label: "Cosmic Energy Healing", value: "Cosmic Energy Healing" },
//   { label: "CosmoEnergy", value: "CosmoEnergy" },
//   { label: "Counseling", value: "Counseling" },
//   { label: "Craniosacral Therapy", value: "Craniosacral Therapy" },
//   { label: "Creative Healing", value: "Creative Healing" },
//   { label: "Crystal Healing", value: "Crystal Healing" },
//   { label: "Crystal Reiki", value: "Crystal Reiki" },
//   { label: "Cupping Therapy", value: "Cupping Therapy" },
//   { label: "Curanderismo", value: "Curanderismo" },
//   { label: "Dance Therapy", value: "Dance Therapy" },
//   { label: "Detoxification", value: "Detoxification" },
//   { label: "Doula Care", value: "Doula Care" },
//   { label: "Drumming Therapy", value: "Drumming Therapy" },
//   { label: "EFT", value: "EFT" },
//   { label: "EMDR", value: "EMDR" },
//   { label: "Embodiment Coaching", value: "Embodiment Coaching" },
//   { label: "Emotion Code", value: "Emotion Code" },
//   { label: "Energy Healing", value: "Energy Healing" },
//   { label: "Equine Therapy", value: "Equine Therapy" },
//   { label: "Expressive Arts Therapy", value: "Expressive Arts Therapy" },
//   { label: "Fascial Maneuvers", value: "Fascial Maneuvers" },
//   { label: "Feldenkrais Method", value: "Feldenkrais Method" },
//   { label: "Feng Shui", value: "Feng Shui" },
//   { label: "Fertility Coaching", value: "Fertility Coaching" },
//   { label: "Flower Essence", value: "Flower Essence" },
//   { label: "Foot Reflexology", value: "Foot Reflexology" },
//   { label: "Forest Bathing", value: "Forest Bathing" },
//   { label: "Frequency Healing", value: "Frequency Healing" },
//   { label: "Functional Medicine", value: "Functional Medicine" },
//   { label: "Geo Love Healing", value: "Geo Love Healing" },
//   { label: "Gong Baths", value: "Gong Baths" },
//   { label: "Hatha Yoga", value: "Hatha Yoga" },
//   { label: "Health Coaching", value: "Health Coaching" },
//   { label: "Heart Rhythm Meditation", value: "Heart Rhythm Meditation" },
//   { label: "HeartMath", value: "HeartMath" },
//   { label: "Herbalism", value: "Herbalism" },
//   { label: "Holistic Beauty & Makeup", value: "Holistic Beauty & Makeup" },
//   { label: "Holistic Hair Care", value: "Holistic Hair Care" },
//   { label: "Holistic Vision Care", value: "Holistic Vision Care" },
//   { label: "Homeopathy", value: "Homeopathy" },
//   { label: "Human Design", value: "Human Design" },
//   { label: "Huna Healing", value: "Huna Healing" },
//   { label: "Hypnotherapy", value: "Hypnotherapy" },
//   {
//     label: "Integral Eye Movement Therapy",
//     value: "Integral Eye Movement Therapy",
//   },
//   { label: "Integrated Energy Therapy", value: "Integrated Energy Therapy" },
//   { label: "IntenSati", value: "IntenSati" },
//   { label: "Intuition Activation", value: "Intuition Activation" },
//   { label: "Intuitive Reading", value: "Intuitive Reading" },
//   { label: "Iridology", value: "Iridology" },
//   { label: "Iyengar Yoga", value: "Iyengar Yoga" },
//   { label: "Jin Shin Jyutsu", value: "Jin Shin Jyutsu" },
//   { label: "Juggling Therapy", value: "Juggling Therapy" },
//   { label: "Jyorei", value: "Jyorei" },
//   { label: "Kinesiology", value: "Kinesiology" },
//   { label: "Kinesiology Taping", value: "Kinesiology Taping" },
//   { label: "Kundalini Yoga", value: "Kundalini Yoga" },
//   { label: "Lama Fera", value: "Lama Fera" },
//   { label: "Life Activation", value: "Life Activation" },
//   { label: "Life Coaching", value: "Life Coaching" },
//   { label: "Light Body Activation", value: "Light Body Activation" },
//   { label: "Light Language", value: "Light Language" },
//   { label: "Light Language Activation", value: "Light Language Activation" },
//   { label: "Lightfield", value: "Lightfield" },
//   { label: "Longevity Coaching", value: "Longevity Coaching" },
//   { label: "MAP Method", value: "MAP Method" },
//   { label: "Magnetic Therapy", value: "Magnetic Therapy" },
//   { label: "Manifestation", value: "Manifestation" },
//   { label: "Marconics", value: "Marconics" },
//   { label: "Martial Arts", value: "Martial Arts" },
//   { label: "Massage Therapy", value: "Massage Therapy" },
//   { label: "Matrix Energetics", value: "Matrix Energetics" },
//   { label: "MediSounds", value: "MediSounds" },
//   { label: "Medical Intuition", value: "Medical Intuition" },
//   { label: "Medicine Wheel", value: "Medicine Wheel" },
//   { label: "Meditation", value: "Meditation" },
//   { label: "Meditation Coaching", value: "Meditation Coaching" },
//   { label: "Menstrual Cycle Awareness", value: "Menstrual Cycle Awareness" },
//   { label: "Mental Health Coaching", value: "Mental Health Coaching" },
//   { label: "Mentoring", value: "Mentoring" },
//   { label: "Metaphysical Counseling", value: "Metaphysical Counseling" },
//   { label: "Mind Healing", value: "Mind Healing" },
//   { label: "Mindfulness", value: "Mindfulness" },
//   { label: "Music Therapy", value: "Music Therapy" },
//   {
//     label: "Native American Healing Practices",
//     value: "Native American Healing Practices",
//   },
//   { label: "Naturopathic Medicine", value: "Naturopathic Medicine" },
//   { label: "Neural Retraining", value: "Neural Retraining" },
//   { label: "Neuro Emotional Technique", value: "Neuro Emotional Technique" },
//   { label: "Neuro Meditation", value: "Neuro Meditation" },
//   {
//     label: "Neuro-linguistic Programming",
//     value: "Neuro-linguistic Programming",
//   },
//   { label: "Neurofeedback", value: "Neurofeedback" },
//   { label: "Neurosculpting", value: "Neurosculpting" },
//   { label: "Nutrition Coaching", value: "Nutrition Coaching" },
//   { label: "Nutritional Therapy", value: "Nutritional Therapy" },
//   { label: "Occupational Therapy", value: "Occupational Therapy" },
//   { label: "One Light Healing Touch", value: "One Light Healing Touch" },
//   { label: "Oracle Reading", value: "Oracle Reading" },
//   { label: "Osteomyology", value: "Osteomyology" },
//   { label: "Osteopathy", value: "Osteopathy" },
//   { label: "Other", value: "Other" },
//   { label: "PSYCH-K", value: "PSYCH-K" },
//   { label: "Past Life Regression", value: "Past Life Regression" },
//   { label: "Pelvic Floor Therapy", value: "Pelvic Floor Therapy" },
//   { label: "Physical Therapy", value: "Physical Therapy" },
//   { label: "Pilates", value: "Pilates" },
//   { label: "Polarity Therapy", value: "Polarity Therapy" },
//   { label: "Polyvagal Theory Practices", value: "Polyvagal Theory Practices" },
//   { label: "Postpartum Support", value: "Postpartum Support" },
//   { label: "Pranic Healing", value: "Pranic Healing" },
//   { label: "Prenatal Wellness", value: "Prenatal Wellness" },
//   { label: "Prenatal Yoga", value: "Prenatal Yoga" },
//   {
//     label: "Progressive Muscle Relaxation",
//     value: "Progressive Muscle Relaxation",
//   },
//   { label: "Psychic Healing", value: "Psychic Healing" },
//   { label: "Psychopomp", value: "Psychopomp" },
//   { label: "Psychotherapy", value: "Psychotherapy" },
//   { label: "Qi Men Dun Jia", value: "Qi Men Dun Jia" },
//   { label: "Qigong", value: "Qigong" },
//   { label: "Quantum Healing", value: "Quantum Healing" },
//   { label: "Quantum Touch", value: "Quantum Touch" },
//   { label: "Radionics", value: "Radionics" },
//   {
//     label: "Rapid Transformational Therapy",
//     value: "Rapid Transformational Therapy",
//   },
//   { label: "Recreational Therapy", value: "Recreational Therapy" },
//   { label: "Reflexology", value: "Reflexology" },
//   { label: "Reiki", value: "Reiki" },
//   { label: "Relationship Coaching", value: "Relationship Coaching" },
//   { label: "Restorative Yoga", value: "Restorative Yoga" },
//   { label: "Rubenfeld Synergy", value: "Rubenfeld Synergy" },
//   { label: "Salt Therapy", value: "Salt Therapy" },
//   { label: "Self-hypnosis", value: "Self-hypnosis" },
//   { label: "Sensory Healing", value: "Sensory Healing" },
//   { label: "Shamanic Journeying", value: "Shamanic Journeying" },
//   { label: "Shamanic Reiki", value: "Shamanic Reiki" },
//   { label: "Shamanism", value: "Shamanism" },
//   { label: "Shiatsu", value: "Shiatsu" },
//   { label: "Siddha Medicine", value: "Siddha Medicine" },
//   { label: "Sigils", value: "Sigils" },
//   { label: "Somatic Therapy", value: "Somatic Therapy" },
//   { label: "Sonopuncture", value: "Sonopuncture" },
//   { label: "Soul Listening", value: "Soul Listening" },
//   { label: "Soul Retrieval", value: "Soul Retrieval" },
//   { label: "SoulCollage", value: "SoulCollage" },
//   { label: "Sound Healing", value: "Sound Healing" },
//   { label: "Sound Therapy", value: "Sound Therapy" },
//   { label: "Spinal Flow Technique", value: "Spinal Flow Technique" },
//   { label: "Spiritual Coaching", value: "Spiritual Coaching" },
//   { label: "Spiritual Entrepreneurship", value: "Spiritual Entrepreneurship" },
//   { label: "Spiritual Mind Treatment", value: "Spiritual Mind Treatment" },
//   { label: "Spiritual Response Therapy", value: "Spiritual Response Therapy" },
//   { label: "Spirituality", value: "Spirituality" },
//   {
//     label: "Systemic Family Constellation",
//     value: "Systemic Family Constellation",
//   },
//   { label: "Tai Chi", value: "Tai Chi" },
//   { label: "Tantra", value: "Tantra" },
//   { label: "Tantric Yoga", value: "Tantric Yoga" },
//   { label: "Tarot Reading", value: "Tarot Reading" },
//   { label: "Thai Bodywork", value: "Thai Bodywork" },
//   { label: "Thai Massage", value: "Thai Massage" },
//   { label: "Therapeutic Touch", value: "Therapeutic Touch" },
//   { label: "Theta Healing", value: "Theta Healing" },
//   { label: "Thought Field Therapy", value: "Thought Field Therapy" },
//   { label: "Tibetan Singing Bowls", value: "Tibetan Singing Bowls" },
//   {
//     label: "Traditional Chinese Medicine",
//     value: "Traditional Chinese Medicine",
//   },
//   {
//     label: "Traditional Japanese Medicine",
//     value: "Traditional Japanese Medicine",
//   },
//   {
//     label: "Traditional Korean Medicine",
//     value: "Traditional Korean Medicine",
//   },
//   {
//     label: "Traditional Mongolian Medicine",
//     value: "Traditional Mongolian Medicine",
//   },
//   {
//     label: "Traditional Tibetan Medicine",
//     value: "Traditional Tibetan Medicine",
//   },
//   { label: "Trance Healing", value: "Trance Healing" },
//   { label: "Transcendental Meditation", value: "Transcendental Meditation" },
//   { label: "Transformational Coaching", value: "Transformational Coaching" },
//   { label: "Trauma-Informed Yoga", value: "Trauma-Informed Yoga" },
//   { label: "Tuina", value: "Tuina" },
//   { label: "Tuning Forks", value: "Tuning Forks" },
//   { label: "Vibrational Therapy", value: "Vibrational Therapy" },
//   { label: "Vinyasa Yoga", value: "Vinyasa Yoga" },
//   { label: "Vipassana", value: "Vipassana" },
//   { label: "Visualization", value: "Visualization" },
//   { label: "Vocal Activation", value: "Vocal Activation" },
//   { label: "Vocal Toning", value: "Vocal Toning" },
//   { label: "Voice Healing Therapy", value: "Voice Healing Therapy" },
//   { label: "Voice Therapy", value: "Voice Therapy" },
//   { label: "Wellness Coaching", value: "Wellness Coaching" },
//   { label: "Women's Health Coaching", value: "Women's Health Coaching" },
//   { label: "Yagerian Therapy", value: "Yagerian Therapy" },
//   { label: "Yin Yoga", value: "Yin Yoga" },
//   { label: "Yoga", value: "Yoga" },
//   { label: "Yoga Therapy", value: "Yoga Therapy" },
//   { label: "Zang Fu Theory", value: "Zang Fu Theory" },
//   { label: "Zenthai Shiatsu Therapy", value: "Zenthai Shiatsu Therapy" },
//   { label: "Other", value: "Other" },
// ];

export const disciplineOptions = [
  { label: "Animal Healing", value: "Animal Healing", key: "animal_healing" },
  { label: "Animal Reiki", value: "Animal Reiki", key: "animal_reiki" },
  { label: "Apitherapy", value: "Apitherapy", key: "apitherapy" },
  { label: "Aromatherapy", value: "Aromatherapy", key: "aromatherapy" },
  { label: "Art Therapy", value: "Art Therapy", key: "art_therapy" },
  { label: "Acupressure", value: "Acupressure", key: "acupressure" },
  { label: "Acupuncture", value: "Acupuncture", key: "acupuncture" },
  {
    label: "Akashic Healing",
    value: "Akashic Healing",
    key: "akashic_healing",
  },
  {
    label: "Akashic Records",
    value: "Akashic Records",
    key: "akashic_records",
  },
  {
    label: "13th Octave LaHoChi",
    value: "13th Octave LaHoChi",
    key: "13th_octave_lahochi",
  },
  {
    label: "Aboriginal Bush Medicine",
    value: "Aboriginal Bush Medicine",
    key: "aboriginal_bush_medicine",
  },
  {
    label: "Access Bars Therapy",
    value: "Access Bars Therapy",
    key: "access_bars_therapy",
  },
  {
    label: "Access Body Processes",
    value: "Access Body Processes",
    key: "access_body_processes",
  },
  {
    label: "Alexander Technique",
    value: "Alexander Technique",
    key: "alexander_technique",
  },
  {
    label: "Alternative Medicine",
    value: "Alternative Medicine",
    key: "alternative_medicine",
  },
  { label: "Angelic Light", value: "Angelic Light", key: "angelic_light" },
  { label: "Ashtanga Yoga", value: "Ashtanga Yoga", key: "ashtanga_yoga" },
  {
    label: "Assisted Stretching",
    value: "Assisted Stretching",
    key: "assisted_stretching",
  },
  { label: "Astrology", value: "Astrology", key: "astrology" },
  { label: "Attunement", value: "Attunement", key: "attunement" },
  { label: "Aura Healing", value: "Aura Healing", key: "aura_healing" },
  {
    label: "Auriculotherapy",
    value: "Auriculotherapy",
    key: "auriculotherapy",
  },
  {
    label: "Autogenic Training",
    value: "Autogenic Training",
    key: "autogenic_training",
  },
  { label: "Autosuggestion", value: "Autosuggestion", key: "autosuggestion" },
  { label: "Ayurveda", value: "Ayurveda", key: "ayurveda" },
  {
    label: "Bach Flower Therapy",
    value: "Bach Flower Therapy",
    key: "bach_flower_therapy",
  },
  { label: "Belief Code", value: "Belief Code", key: "belief_code" },
  { label: "Bikram Yoga", value: "Bikram Yoga", key: "bikram_yoga" },
  {
    label: "Bilateral Stimulation",
    value: "Bilateral Stimulation",
    key: "bilateral_stimulation",
  },
  { label: "Binaural Beats", value: "Binaural Beats", key: "binaural_beats" },
  { label: "Bio-Well", value: "Bio-Well", key: "bio_well" },
  {
    label: "Bio-magnetic Therapy",
    value: "Bio-magnetic Therapy",
    key: "bio_magnetic_therapy",
  },
  {
    label: "Biodynamic Craniosacral Therapy",
    value: "Biodynamic Craniosacral Therapy",
    key: "biodynamic_craniosacral_therapy",
  },
  {
    label: "Biofield Tuning",
    value: "Biofield Tuning",
    key: "biofield_tuning",
  },
  {
    label: "Biophoton Therapy",
    value: "Biophoton Therapy",
    key: "biophoton_therapy",
  },
  { label: "Body Alignment", value: "Body Alignment", key: "body_alignment" },
  { label: "Body Code", value: "Body Code", key: "body_code" },
  { label: "Body Healing", value: "Body Healing", key: "body_healing" },
  { label: "Bowen Therapy", value: "Bowen Therapy", key: "bowen_therapy" },
  {
    label: "Breathwork Therapy",
    value: "Breathwork Therapy",
    key: "breathwork_therapy",
  },
  {
    label: "Brennan Healing Science",
    value: "Brennan Healing Science",
    key: "brennan_healing_science",
  },
  { label: "Chair Yoga", value: "Chair Yoga", key: "chair_yoga" },
  { label: "Chakra Healing", value: "Chakra Healing", key: "chakra_healing" },
  { label: "Children Yoga", value: "Children Yoga", key: "children_yoga" },
  { label: "Chiropractic", value: "Chiropractic", key: "chiropractic" },
  { label: "Chromotherapy", value: "Chromotherapy", key: "chromotherapy" },
  {
    label: "Chumpi Illumination",
    value: "Chumpi Illumination",
    key: "chumpi_illumination",
  },
  { label: "Coaching", value: "Coaching", key: "coaching" },
  {
    label: "Conscious Leadership Training",
    value: "Conscious Leadership Training",
    key: "conscious_leadership_training",
  },
  {
    label: "Cosmic Energy Healing",
    value: "Cosmic Energy Healing",
    key: "cosmic_energy_healing",
  },
  { label: "CosmoEnergy", value: "CosmoEnergy", key: "cosmoenergy" },
  { label: "Counseling", value: "Counseling", key: "counseling" },
  {
    label: "Craniosacral Therapy",
    value: "Craniosacral Therapy",
    key: "craniosacral_therapy",
  },
  {
    label: "Creative Healing",
    value: "Creative Healing",
    key: "creative_healing",
  },
  {
    label: "Crystal Healing",
    value: "Crystal Healing",
    key: "crystal_healing",
  },
  { label: "Crystal Reiki", value: "Crystal Reiki", key: "crystal_reiki" },
  {
    label: "Cupping Therapy",
    value: "Cupping Therapy",
    key: "cupping_therapy",
  },
  { label: "Curanderismo", value: "Curanderismo", key: "curanderismo" },
  { label: "Dance Therapy", value: "Dance Therapy", key: "dance_therapy" },
  { label: "Detoxification", value: "Detoxification", key: "detoxification" },
  { label: "Doula Care", value: "Doula Care", key: "doula_care" },
  {
    label: "Drumming Therapy",
    value: "Drumming Therapy",
    key: "drumming_therapy",
  },
  { label: "EFT", value: "EFT", key: "eft" },
  { label: "EMDR", value: "EMDR", key: "emdr" },
  {
    label: "Embodiment Coaching",
    value: "Embodiment Coaching",
    key: "embodiment_coaching",
  },
  { label: "Emotion Code", value: "Emotion Code", key: "emotion_code" },
  { label: "Energy Healing", value: "Energy Healing", key: "energy_healing" },
  { label: "Equine Therapy", value: "Equine Therapy", key: "equine_therapy" },
  {
    label: "Expressive Arts Therapy",
    value: "Expressive Arts Therapy",
    key: "expressive_arts_therapy",
  },
  {
    label: "Fascial Maneuvers",
    value: "Fascial Maneuvers",
    key: "fascial_maneuvers",
  },
  {
    label: "Feldenkrais Method",
    value: "Feldenkrais Method",
    key: "feldenkrais_method",
  },
  { label: "Feng Shui", value: "Feng Shui", key: "feng_shui" },
  {
    label: "Fertility Coaching",
    value: "Fertility Coaching",
    key: "fertility_coaching",
  },
  { label: "Flower Essence", value: "Flower Essence", key: "flower_essence" },
  {
    label: "Foot Reflexology",
    value: "Foot Reflexology",
    key: "foot_reflexology",
  },
  { label: "Forest Bathing", value: "Forest Bathing", key: "forest_bathing" },
  {
    label: "Frequency Healing",
    value: "Frequency Healing",
    key: "frequency_healing",
  },
  {
    label: "Functional Medicine",
    value: "Functional Medicine",
    key: "functional_medicine",
  },
  {
    label: "Geo Love Healing",
    value: "Geo Love Healing",
    key: "geo_love_healing",
  },
  { label: "Gong Baths", value: "Gong Baths", key: "gong_baths" },
  { label: "Hatha Yoga", value: "Hatha Yoga", key: "hatha_yoga" },
  {
    label: "Health Coaching",
    value: "Health Coaching",
    key: "health_coaching",
  },
  {
    label: "Heart Rhythm Meditation",
    value: "Heart Rhythm Meditation",
    key: "heart_rhythm_meditation",
  },
  { label: "HeartMath", value: "HeartMath", key: "heartmath" },
  { label: "Herbalism", value: "Herbalism", key: "herbalism" },
  {
    label: "Holistic Beauty & Makeup",
    value: "Holistic Beauty & Makeup",
    key: "holistic_beauty_and_makeup",
  },
  {
    label: "Holistic Hair Care",
    value: "Holistic Hair Care",
    key: "holistic_hair_care",
  },
  {
    label: "Holistic Vision Care",
    value: "Holistic Vision Care",
    key: "holistic_vision_care",
  },
  { label: "Homeopathy", value: "Homeopathy", key: "homeopathy" },
  { label: "Human Design", value: "Human Design", key: "human_design" },
  { label: "Huna Healing", value: "Huna Healing", key: "huna_healing" },
  { label: "Hypnotherapy", value: "Hypnotherapy", key: "hypnotherapy" },
  {
    label: "Integral Eye Movement Therapy",
    value: "Integral Eye Movement Therapy",
    key: "integral_eye_movement_therapy",
  },
  {
    label: "Integrated Energy Therapy",
    value: "Integrated Energy Therapy",
    key: "integrated_energy_therapy",
  },
  { label: "IntenSati", value: "IntenSati", key: "intensati" },
  {
    label: "Intuition Activation",
    value: "Intuition Activation",
    key: "intuition_activation",
  },
  {
    label: "Intuitive Reading",
    value: "Intuitive Reading",
    key: "intuitive_reading",
  },
  { label: "Iridology", value: "Iridology", key: "iridology" },
  { label: "Iyengar Yoga", value: "Iyengar Yoga", key: "iyengar_yoga" },
  {
    label: "Jin Shin Jyutsu",
    value: "Jin Shin Jyutsu",
    key: "jin_shin_jyutsu",
  },
  {
    label: "Juggling Therapy",
    value: "Juggling Therapy",
    key: "juggling_therapy",
  },
  { label: "Jyorei", value: "Jyorei", key: "jyorei" },
  { label: "Kinesiology", value: "Kinesiology", key: "kinesiology" },
  {
    label: "Kinesiology Taping",
    value: "Kinesiology Taping",
    key: "kinesiology_taping",
  },
  { label: "Kundalini Yoga", value: "Kundalini Yoga", key: "kundalini_yoga" },
  { label: "Lama Fera", value: "Lama Fera", key: "lama_fera" },
  {
    label: "Life Activation",
    value: "Life Activation",
    key: "life_activation",
  },
  { label: "Life Coaching", value: "Life Coaching", key: "life_coaching" },
  {
    label: "Light Body Activation",
    value: "Light Body Activation",
    key: "light_body_activation",
  },
  { label: "Light Language", value: "Light Language", key: "light_language" },
  {
    label: "Light Language Activation",
    value: "Light Language Activation",
    key: "light_language_activation",
  },
  { label: "Lightfield", value: "Lightfield", key: "lightfield" },
  {
    label: "Longevity Coaching",
    value: "Longevity Coaching",
    key: "longevity_coaching",
  },
  { label: "MAP Method", value: "MAP Method", key: "map_method" },
  {
    label: "Magnetic Therapy",
    value: "Magnetic Therapy",
    key: "magnetic_therapy",
  },
  { label: "Manifestation", value: "Manifestation", key: "manifestation" },
  { label: "Marconics", value: "Marconics", key: "marconics" },
  { label: "Martial Arts", value: "Martial Arts", key: "martial_arts" },
  {
    label: "Massage Therapy",
    value: "Massage Therapy",
    key: "massage_therapy",
  },
  {
    label: "Matrix Energetics",
    value: "Matrix Energetics",
    key: "matrix_energetics",
  },
  { label: "MediSounds", value: "MediSounds", key: "medisounds" },
  {
    label: "Medical Intuition",
    value: "Medical Intuition",
    key: "medical_intuition",
  },
  { label: "Medicine Wheel", value: "Medicine Wheel", key: "medicine_wheel" },
  { label: "Meditation", value: "Meditation", key: "meditation" },
  {
    label: "Meditation Coaching",
    value: "Meditation Coaching",
    key: "meditation_coaching",
  },
  {
    label: "Menstrual Cycle Awareness",
    value: "Menstrual Cycle Awareness",
    key: "menstrual_cycle_awareness",
  },
  {
    label: "Mental Health Coaching",
    value: "Mental Health Coaching",
    key: "mental_health_coaching",
  },
  { label: "Mentoring", value: "Mentoring", key: "mentoring" },
  {
    label: "Metaphysical Counseling",
    value: "Metaphysical Counseling",
    key: "metaphysical_counseling",
  },
  { label: "Mind Healing", value: "Mind Healing", key: "mind_healing" },
  { label: "Mindfulness", value: "Mindfulness", key: "mindfulness" },
  { label: "Music Therapy", value: "Music Therapy", key: "music_therapy" },
  {
    label: "Native American Healing Practices",
    value: "Native American Healing Practices",
    key: "native_american_healing_practices",
  },
  {
    label: "Naturopathic Medicine",
    value: "Naturopathic Medicine",
    key: "naturopathic_medicine",
  },
  {
    label: "Neural Retraining",
    value: "Neural Retraining",
    key: "neural_retraining",
  },
  {
    label: "Neuro Emotional Technique",
    value: "Neuro Emotional Technique",
    key: "neuro_emotional_technique",
  },
  {
    label: "Neuro Meditation",
    value: "Neuro Meditation",
    key: "neuro_meditation",
  },
  {
    label: "Neuro-linguistic Programming",
    value: "Neuro-linguistic Programming",
    key: "neuro_linguistic_programming",
  },
  { label: "Neurofeedback", value: "Neurofeedback", key: "neurofeedback" },
  { label: "Neurosculpting", value: "Neurosculpting", key: "neurosculpting" },
  {
    label: "Nutrition Coaching",
    value: "Nutrition Coaching",
    key: "nutrition_coaching",
  },
  {
    label: "Nutritional Therapy",
    value: "Nutritional Therapy",
    key: "nutritional_therapy",
  },
  {
    label: "Occupational Therapy",
    value: "Occupational Therapy",
    key: "occupational_therapy",
  },
  {
    label: "One Light Healing Touch",
    value: "One Light Healing Touch",
    key: "one_light_healing_touch",
  },
  { label: "Oracle Reading", value: "Oracle Reading", key: "oracle_reading" },
  { label: "Osteomyology", value: "Osteomyology", key: "osteomyology" },
  { label: "Osteopathy", value: "Osteopathy", key: "osteopathy" },
  { label: "Other", value: "Other", key: "other" },
  { label: "PSYCH-K", value: "PSYCH-K", key: "psych_k" },
  {
    label: "Past Life Regression",
    value: "Past Life Regression",
    key: "past_life_regression",
  },
  {
    label: "Pelvic Floor Therapy",
    value: "Pelvic Floor Therapy",
    key: "pelvic_floor_therapy",
  },
  {
    label: "Physical Therapy",
    value: "Physical Therapy",
    key: "physical_therapy",
  },
  { label: "Pilates", value: "Pilates", key: "pilates" },
  {
    label: "Polarity Therapy",
    value: "Polarity Therapy",
    key: "polarity_therapy",
  },
  {
    label: "Polyvagal Theory Practices",
    value: "Polyvagal Theory Practices",
    key: "polyvagal_theory_practices",
  },
  {
    label: "Postpartum Support",
    value: "Postpartum Support",
    key: "postpartum_support",
  },
  { label: "Pranic Healing", value: "Pranic Healing", key: "pranic_healing" },
  {
    label: "Prenatal Wellness",
    value: "Prenatal Wellness",
    key: "prenatal_wellness",
  },
  { label: "Prenatal Yoga", value: "Prenatal Yoga", key: "prenatal_yoga" },
  {
    label: "Progressive Muscle Relaxation",
    value: "Progressive Muscle Relaxation",
    key: "progressive_muscle_relaxation",
  },
  {
    label: "Psychic Healing",
    value: "Psychic Healing",
    key: "psychic_healing",
  },
  { label: "Psychopomp", value: "Psychopomp", key: "psychopomp" },
  { label: "Psychotherapy", value: "Psychotherapy", key: "psychotherapy" },
  { label: "Qi Men Dun Jia", value: "Qi Men Dun Jia", key: "qi_men_dun_jia" },
  { label: "Qigong", value: "Qigong", key: "qigong" },
  {
    label: "Quantum Healing",
    value: "Quantum Healing",
    key: "quantum_healing",
  },
  { label: "Quantum Touch", value: "Quantum Touch", key: "quantum_touch" },
  { label: "Radionics", value: "Radionics", key: "radionics" },
  {
    label: "Rapid Transformational Therapy",
    value: "Rapid Transformational Therapy",
    key: "rapid_transformational_therapy",
  },
  {
    label: "Recreational Therapy",
    value: "Recreational Therapy",
    key: "recreational_therapy",
  },
  { label: "Reflexology", value: "Reflexology", key: "reflexology" },
  { label: "Reiki", value: "Reiki", key: "reiki" },
  {
    label: "Relationship Coaching",
    value: "Relationship Coaching",
    key: "relationship_coaching",
  },
  {
    label: "Restorative Yoga",
    value: "Restorative Yoga",
    key: "restorative_yoga",
  },
  {
    label: "Rubenfeld Synergy",
    value: "Rubenfeld Synergy",
    key: "rubenfeld_synergy",
  },
  { label: "Salt Therapy", value: "Salt Therapy", key: "salt_therapy" },
  { label: "Self-hypnosis", value: "Self-hypnosis", key: "self_hypnosis" },
  {
    label: "Sensory Healing",
    value: "Sensory Healing",
    key: "sensory_healing",
  },
  {
    label: "Shamanic Journeying",
    value: "Shamanic Journeying",
    key: "shamanic_journeying",
  },
  { label: "Shamanic Reiki", value: "Shamanic Reiki", key: "shamanic_reiki" },
  { label: "Shamanism", value: "Shamanism", key: "shamanism" },
  { label: "Shiatsu", value: "Shiatsu", key: "shiatsu" },
  {
    label: "Siddha Medicine",
    value: "Siddha Medicine",
    key: "siddha_medicine",
  },
  { label: "Sigils", value: "Sigils", key: "sigils" },
  {
    label: "Somatic Therapy",
    value: "Somatic Therapy",
    key: "somatic_therapy",
  },
  { label: "Sonopuncture", value: "Sonopuncture", key: "sonopuncture" },
  { label: "Soul Listening", value: "Soul Listening", key: "soul_listening" },
  { label: "Soul Retrieval", value: "Soul Retrieval", key: "soul_retrieval" },
  { label: "SoulCollage", value: "SoulCollage", key: "soulcollage" },
  { label: "Sound Healing", value: "Sound Healing", key: "sound_healing" },
  { label: "Sound Therapy", value: "Sound Therapy", key: "sound_therapy" },
  {
    label: "Spinal Flow Technique",
    value: "Spinal Flow Technique",
    key: "spinal_flow_technique",
  },
  {
    label: "Spiritual Coaching",
    value: "Spiritual Coaching",
    key: "spiritual_coaching",
  },
  {
    label: "Spiritual Entrepreneurship",
    value: "Spiritual Entrepreneurship",
    key: "spiritual_entrepreneurship",
  },
  {
    label: "Spiritual Mind Treatment",
    value: "Spiritual Mind Treatment",
    key: "spiritual_mind_treatment",
  },
  {
    label: "Spiritual Response Therapy",
    value: "Spiritual Response Therapy",
    key: "spiritual_response_therapy",
  },
  { label: "Spirituality", value: "Spirituality", key: "spirituality" },
  {
    label: "Systemic Family Constellation",
    value: "Systemic Family Constellation",
    key: "systemic_family_constellation",
  },
  { label: "Tai Chi", value: "Tai Chi", key: "tai_chi" },
  { label: "Tantra", value: "Tantra", key: "tantra" },
  { label: "Tantric Yoga", value: "Tantric Yoga", key: "tantric_yoga" },
  { label: "Tarot Reading", value: "Tarot Reading", key: "tarot_reading" },
  { label: "Thai Bodywork", value: "Thai Bodywork", key: "thai_bodywork" },
  { label: "Thai Massage", value: "Thai Massage", key: "thai_massage" },
  {
    label: "Therapeutic Touch",
    value: "Therapeutic Touch",
    key: "therapeutic_touch",
  },
  { label: "Theta Healing", value: "Theta Healing", key: "theta_healing" },
  {
    label: "Thought Field Therapy",
    value: "Thought Field Therapy",
    key: "thought_field_therapy",
  },
  {
    label: "Tibetan Singing Bowls",
    value: "Tibetan Singing Bowls",
    key: "tibetan_singing_bowls",
  },
  {
    label: "Traditional Chinese Medicine",
    value: "Traditional Chinese Medicine",
    key: "traditional_chinese_medicine",
  },
  {
    label: "Traditional Japanese Medicine",
    value: "Traditional Japanese Medicine",
    key: "traditional_japanese_medicine",
  },
  {
    label: "Traditional Korean Medicine",
    value: "Traditional Korean Medicine",
    key: "traditional_korean_medicine",
  },
  {
    label: "Traditional Mongolian Medicine",
    value: "Traditional Mongolian Medicine",
    key: "traditional_mongolian_medicine",
  },
  {
    label: "Traditional Tibetan Medicine",
    value: "Traditional Tibetan Medicine",
    key: "traditional_tibetan_medicine",
  },
  { label: "Trance Healing", value: "Trance Healing", key: "trance_healing" },
  {
    label: "Transcendental Meditation",
    value: "Transcendental Meditation",
    key: "transcendental_meditation",
  },
  {
    label: "Transformational Coaching",
    value: "Transformational Coaching",
    key: "transformational_coaching",
  },
  {
    label: "Trauma-Informed Yoga",
    value: "Trauma-Informed Yoga",
    key: "trauma_informed_yoga",
  },
  { label: "Tuina", value: "Tuina", key: "tuina" },
  { label: "Tuning Forks", value: "Tuning Forks", key: "tuning_forks" },
  {
    label: "Vibrational Therapy",
    value: "Vibrational Therapy",
    key: "vibrational_therapy",
  },
  { label: "Vinyasa Yoga", value: "Vinyasa Yoga", key: "vinyasa_yoga" },
  { label: "Vipassana", value: "Vipassana", key: "vipassana" },
  { label: "Visualization", value: "Visualization", key: "visualization" },
  {
    label: "Vocal Activation",
    value: "Vocal Activation",
    key: "vocal_activation",
  },
  { label: "Vocal Toning", value: "Vocal Toning", key: "vocal_toning" },
  {
    label: "Voice Healing Therapy",
    value: "Voice Healing Therapy",
    key: "voice_healing_therapy",
  },
  { label: "Voice Therapy", value: "Voice Therapy", key: "voice_therapy" },
  {
    label: "Wellness Coaching",
    value: "Wellness Coaching",
    key: "wellness_coaching",
  },
  {
    label: "Women's Health Coaching",
    value: "Women's Health Coaching",
    key: "womens_health_coaching",
  },
  {
    label: "Yagerian Therapy",
    value: "Yagerian Therapy",
    key: "yagerian_therapy",
  },
  { label: "Yin Yoga", value: "Yin Yoga", key: "yin_yoga" },
  { label: "Yoga", value: "Yoga", key: "yoga" },
  { label: "Yoga Therapy", value: "Yoga Therapy", key: "yoga_therapy" },
  { label: "Zang Fu Theory", value: "Zang Fu Theory", key: "zang_fu_theory" },
  {
    label: "Zenthai Shiatsu Therapy",
    value: "Zenthai Shiatsu Therapy",
    key: "zenthai_shiatsu_therapy",
  },
  { label: "Other", value: "Other", key: "other_2" },
];

export const genderOptions = [
  { label: "Male", value: "male" },
  { label: "Female", value: "female" },
  { label: "Others", value: "others" },
];

export const tagsOptions = [
  { label: "Stress relief", value: "stress_relief" },
  { label: "Emotional healing", value: "emotional_healing" },
  { label: "Creativity", value: "creativity" },
  { label: "Self Discovery", value: "self_discovery" },
  { label: "Women's wellness", value: "womens_wellness" },
  { label: "Spiritual growth", value: "spiritual_growth" },
  { label: "Sleep improvement", value: "sleep_improvement" },
  { label: "Inner child healing", value: "inner_child_healing" },
  { label: "Energy balancing", value: "energy_balancing" },
  { label: "Physical recovery", value: "physical_recovery" },
  { label: "Detox", value: "detox" },
  { label: "Men's wellness", value: "mens_wellness" },
  { label: "Grief support", value: "grief_support" },
  { label: "Chakra balancing", value: "chakra_balancing" },
  { label: "Burnout recovery", value: "burnout_recovery" },
];

export const accessibilityItem = [
  { label: "Wheelchair accessible", value: "wheelchair_accessible" },
  { label: "Quiet environment", value: "quiet_environment" },
  { label: "Guide dog allowed", value: "guide_dog_allowed" },
  {
    label: "Reserved parking for disabled",
    value: "reserved_parking_for_disabled",
  },
  { label: "Visual support available", value: "visual_support_available" },
  { label: "Braille materials", value: "braille_materials" },
  { label: "Hearing support", value: "hearing_support" },
  { label: "Accessible toilets", value: "accessible_toilets" },
  { label: "Sign language interpreter", value: "sign_language_interpreter" },
  { label: "High readability materials", value: "high_readability_materials" },
  { label: "Cognitive support", value: "cognitive_support" },
  { label: "Elevator available", value: "elevator_available" },
  { label: "Other", value: "other" },
];

export const eventItem = [
  {
    value: "onetoone",
    label: "1:1",
    key: "1:1",
  },
  {
    value: "group",
    label: "Group",
    key: "group",
  },
  {
    value: "retreat",
    label: "Retreat",
    key: "retreat",
  },
];

export const delivaryOptions = [
  { value: "offline", label: "Offline", icon: "offline", key: "offline" },
  { value: "online", label: "Online", icon: "online", key: "online" },
  { value: "ondemand", label: "On demand", icon: "ondemand", key: "on_demand" },
];

export const purposeItem = [
  { value: "educational", label: "Educational" },
  { value: "experimental", label: "Experiential" },
  { value: "mixed", label: "Mixed" },
];

export const durationOptions = [
  { value: "less_than_30_minutes", label: "Less than 30 minutes" },
  { value: "30_60_minutes", label: "30-60 minutes" },
  { value: "1_2_hours", label: "1-2 hours" },
  { value: "half_day", label: "Half day" },
  { value: "one_day", label: "One day" },
  { value: "two_days", label: "Two days" },
  { value: "three_days", label: "Three days" },
  { value: "four_days", label: "Four days" },
  { value: "five_days", label: "Five days" },
  { value: "one_week", label: "One week" },
  { value: "more_than_one_week", label: "More than one week" },
];

export const dateOption = [
  { label: "Today", value: "today" },
  { label: "Tomorrow", value: "tomorrow" },
  { label: "This Month", value: "this_month" },
  { label: "Next Month", value: "next_month" },
];

export const newsLetterOption = [
  {
    label: "User Purchase",
    value: newsletSts.userPurchase,
  },
  {
    label: "Operator Sales",
    value: newsletSts.operatorSales,
  },
  {
    label: "User Metrics",
    value: newsletSts.userMetrics,
  },
  {
    label: "Operator Metrics",
    value: newsletSts.operatorMetrics,
  },
  {
    label: "User Disciplines",
    value: newsletSts.userDisciplines,
  },
  {
    label: "Operator Disciplines",
    value: newsletSts.operatorDisciplines,
  },
  {
    label: "User Event",
    value: newsletSts.userEvent,
  },
  {
    label: "Operator Event",
    value: newsletSts.operatorEvent,
  },
  {
    label: "Purpose",
    value: newsletSts.purpose,
  },
  {
    label: "Tags",
    value: newsletSts.tags,
  },
  {
    label: "Locations",
    value: newsletSts.locations,
  },
  {
    label: "Duration",
    value: newsletSts.duration,
  },
  {
    label: "Price",
    value: newsletSts.price,
  },
  {
    label: "Capacity",
    value: newsletSts.capacity,
  },
  {
    label: "Accessibility",
    value: newsletSts.accessibility,
  },
  {
    label: "Subscribed",
    value: newsletSts.subscribed,
  },
];
