import assets from "@/assets";
import { newsletSts } from "@/lib/constants";

export const featuresData = [
  {
    id: 1,
    title: "Personal Profile",
    text: "Create a customize your account",
    description:
      "Create your own account and add personal details to customize your experience. Update your profile anytime, keep your information secure, and manage your preferences with ease. Your profile is the starting point for exploring and booking events tailored just for you.",
    icon: assets.feature.profile,
    bgColor: "#F7FAFF",
    shadow:
      "0 2px 4px 0 rgba(34, 117, 255, 0.25), 0 -2px 4px 0 rgba(34, 117, 255, 0.25), 2px 0 4px 0 rgba(34, 117, 255, 0.25), -2px 0 4px 0 rgba(34, 117, 255, 0.25)",
  },
  {
    id: 2,
    title: "Event Discovery",
    text: "Create a customize your account",
    description:
      "Explore a wide range of events — from online workshops to in-person conferences. Use advanced filters like location, type, and fee range to quickly find what you're looking for. Save your favorite events and never miss out on opportunities that matter most to you.",
    icon: assets.feature.discovery,
    bgColor: "#FFF5F6",
    iconBgColor: "bg-pink-100",
    shadow:
      "0 2px 4px 0 rgba(255, 18, 56, 0.25), 0 -2px 4px 0 rgba(255, 18, 56, 0.25), 2px 0 4px 0 rgba(255, 18, 56, 0.25), -2px 0 4px 0 rgba(255, 18, 56, 0.25)",
  },
  {
    id: 3,
    title: "Ticketing & Booking",
    text: "Create a customize your account",
    description:
      "Book tickets seamlessly with a secure and reliable checkout process. Once your booking is complete, you'll receive automatic confirmations and receipts. Stay worry-free knowing your tickets are stored in your account and can be accessed anytime.",
    icon: assets.feature.booking,
    bgColor: "#FDF6FF",
    shadow:
      " 0 2px 4px 0 rgba(204, 25, 255, 0.25), 0 -2px 4px 0 rgba(204, 25, 255, 0.25), 2px 0 4px 0 rgba(204, 25, 255, 0.25), -2px 0 4px 0 rgba(204, 25, 255, 0.25)",
  },
  {
    id: 4,
    title: "Reviews & Ratings",
    text: "Create a customize your account",
    description:
      "After attending events, share your honest feedback through ratings and reviews. Your input helps improve the platform and guides other users in choosing the best events. Build a community of trust by voicing your experience and recommendations.",
    icon: assets.feature.rating,
    bgColor: "#FFFDF1",
    shadow:
      "0 2px 4px 0 rgba(255, 221, 14, 0.25), 0 -2px 4px 0 rgba(255, 221, 14, 0.25), 2px 0 4px 0 rgba(255, 221, 14, 0.25), -2px 0 4px 0 rgba(255, 221, 14, 0.25)",
  },
  {
    id: 5,
    title: "Payments & Invoices",
    text: "Create a customize your account",
    description:
      "Manage all your event-related payments in one convenient place. Access detailed invoices, track your booking history, and download receipts whenever you need them. Enjoy transparency and clarity with every transaction you make.",
    icon: assets.feature.payment,
    bgColor: "#F4FCFF",
    shadow:
      " 0 2px 4px 0 rgba(18, 190, 255, 0.25), 0 -2px 4px 0 rgba(18, 190, 255, 0.25), 2px 0 4px 0 rgba(18, 190, 255, 0.25), -2px 0 4px 0 rgba(18, 190, 255, 0.25)",
  },
  {
    id: 6,
    title: "Subscriptions",
    text: "Create a customize your account",
    description:
      "Stay updated by subscribing to event newsletters and notifications. Choose the types of updates you want to receive — from upcoming concerts to professional seminars. With customized subscriptions, you’ll always be in the loop without unnecessary clutter.",
    icon: assets.feature.subscrit,
    bgColor: "#F9FFEE",
    shadow:
      " 0 2px 4px 0 rgba(171, 255, 16, 0.25), 0 -2px 4px 0 rgba(171, 255, 16, 0.25), 2px 0 4px 0 rgba(171, 255, 16, 0.25), -2px 0 4px 0 rgba(171, 255, 16, 0.25)",
  },
];

export const disciplineOptions = [
  { label: "Animal Healing", value: "Animal Healing" },
  { label: "Animal Reiki", value: "Animal Reiki" },
  { label: "Apitherapy", value: "Apitherapy" },
  { label: "Aromatherapy", value: "Aromatherapy" },
  { label: "Art Therapy", value: "Art Therapy" },
  { label: "Acupressure", value: "Acupressure" },
  { label: "Acupuncture", value: "Acupuncture" },
  { label: "Akashic Healing", value: "Akashic Healing" },
  { label: "Akashic Records", value: "Akashic Records" },
  { label: "13th Octave LaHoChi", value: "13th Octave LaHoChi" },
  { label: "Aboriginal Bush Medicine", value: "Aboriginal Bush Medicine" },
  { label: "Access Bars Therapy", value: "Access Bars Therapy" },
  { label: "Access Body Processes", value: "Access Body Processes" },
  { label: "Alexander Technique", value: "Alexander Technique" },
  { label: "Alternative Medicine", value: "Alternative Medicine" },
  { label: "Angelic Light", value: "Angelic Light" },
  { label: "Ashtanga Yoga", value: "Ashtanga Yoga" },
  { label: "Assisted Stretching", value: "Assisted Stretching" },
  { label: "Astrology", value: "Astrology" },
  { label: "Attunement", value: "Attunement" },
  { label: "Aura Healing", value: "Aura Healing" },
  { label: "Auriculotherapy", value: "Auriculotherapy" },
  { label: "Autogenic Training", value: "Autogenic Training" },
  { label: "Autosuggestion", value: "Autosuggestion" },
  { label: "Ayurveda", value: "Ayurveda" },
  { label: "Bach Flower Therapy", value: "Bach Flower Therapy" },
  { label: "Belief Code", value: "Belief Code" },
  { label: "Bikram Yoga", value: "Bikram Yoga" },
  { label: "Bilateral Stimulation", value: "Bilateral Stimulation" },
  { label: "Binaural Beats", value: "Binaural Beats" },
  { label: "Bio-Well", value: "Bio-Well" },
  { label: "Bio-magnetic Therapy", value: "Bio-magnetic Therapy" },
  {
    label: "Biodynamic Craniosacral Therapy",
    value: "Biodynamic Craniosacral Therapy",
  },
  { label: "Biofield Tuning", value: "Biofield Tuning" },
  { label: "Biophoton Therapy", value: "Biophoton Therapy" },
  { label: "Body Alignment", value: "Body Alignment" },
  { label: "Body Code", value: "Body Code" },
  { label: "Body Healing", value: "Body Healing" },
  { label: "Bowen Therapy", value: "Bowen Therapy" },
  { label: "Breathwork Therapy", value: "Breathwork Therapy" },
  { label: "Brennan Healing Science", value: "Brennan Healing Science" },
  { label: "Chair Yoga", value: "Chair Yoga" },
  { label: "Chakra Healing", value: "Chakra Healing" },
  { label: "Children Yoga", value: "Children Yoga" },
  { label: "Chiropractic", value: "Chiropractic" },
  { label: "Chromotherapy", value: "Chromotherapy" },
  { label: "Chumpi Illumination", value: "Chumpi Illumination" },
  { label: "Coaching", value: "Coaching" },
  {
    label: "Conscious Leadership Training",
    value: "Conscious Leadership Training",
  },
  { label: "Cosmic Energy Healing", value: "Cosmic Energy Healing" },
  { label: "CosmoEnergy", value: "CosmoEnergy" },
  { label: "Counseling", value: "Counseling" },
  { label: "Craniosacral Therapy", value: "Craniosacral Therapy" },
  { label: "Creative Healing", value: "Creative Healing" },
  { label: "Crystal Healing", value: "Crystal Healing" },
  { label: "Crystal Reiki", value: "Crystal Reiki" },
  { label: "Cupping Therapy", value: "Cupping Therapy" },
  { label: "Curanderismo", value: "Curanderismo" },
  { label: "Dance Therapy", value: "Dance Therapy" },
  { label: "Detoxification", value: "Detoxification" },
  { label: "Doula Care", value: "Doula Care" },
  { label: "Drumming Therapy", value: "Drumming Therapy" },
  { label: "EFT", value: "EFT" },
  { label: "EMDR", value: "EMDR" },
  { label: "Embodiment Coaching", value: "Embodiment Coaching" },
  { label: "Emotion Code", value: "Emotion Code" },
  { label: "Energy Healing", value: "Energy Healing" },
  { label: "Equine Therapy", value: "Equine Therapy" },
  { label: "Expressive Arts Therapy", value: "Expressive Arts Therapy" },
  { label: "Fascial Maneuvers", value: "Fascial Maneuvers" },
  { label: "Feldenkrais Method", value: "Feldenkrais Method" },
  { label: "Feng Shui", value: "Feng Shui" },
  { label: "Fertility Coaching", value: "Fertility Coaching" },
  { label: "Flower Essence", value: "Flower Essence" },
  { label: "Foot Reflexology", value: "Foot Reflexology" },
  { label: "Forest Bathing", value: "Forest Bathing" },
  { label: "Frequency Healing", value: "Frequency Healing" },
  { label: "Functional Medicine", value: "Functional Medicine" },
  { label: "Geo Love Healing", value: "Geo Love Healing" },
  { label: "Gong Baths", value: "Gong Baths" },
  { label: "Hatha Yoga", value: "Hatha Yoga" },
  { label: "Health Coaching", value: "Health Coaching" },
  { label: "Heart Rhythm Meditation", value: "Heart Rhythm Meditation" },
  { label: "HeartMath", value: "HeartMath" },
  { label: "Herbalism", value: "Herbalism" },
  { label: "Holistic Beauty & Makeup", value: "Holistic Beauty & Makeup" },
  { label: "Holistic Hair Care", value: "Holistic Hair Care" },
  { label: "Holistic Vision Care", value: "Holistic Vision Care" },
  { label: "Homeopathy", value: "Homeopathy" },
  { label: "Human Design", value: "Human Design" },
  { label: "Huna Healing", value: "Huna Healing" },
  { label: "Hypnotherapy", value: "Hypnotherapy" },
  {
    label: "Integral Eye Movement Therapy",
    value: "Integral Eye Movement Therapy",
  },
  { label: "Integrated Energy Therapy", value: "Integrated Energy Therapy" },
  { label: "IntenSati", value: "IntenSati" },
  { label: "Intuition Activation", value: "Intuition Activation" },
  { label: "Intuitive Reading", value: "Intuitive Reading" },
  { label: "Iridology", value: "Iridology" },
  { label: "Iyengar Yoga", value: "Iyengar Yoga" },
  { label: "Jin Shin Jyutsu", value: "Jin Shin Jyutsu" },
  { label: "Juggling Therapy", value: "Juggling Therapy" },
  { label: "Jyorei", value: "Jyorei" },
  { label: "Kinesiology", value: "Kinesiology" },
  { label: "Kinesiology Taping", value: "Kinesiology Taping" },
  { label: "Kundalini Yoga", value: "Kundalini Yoga" },
  { label: "Lama Fera", value: "Lama Fera" },
  { label: "Life Activation", value: "Life Activation" },
  { label: "Life Coaching", value: "Life Coaching" },
  { label: "Light Body Activation", value: "Light Body Activation" },
  { label: "Light Language", value: "Light Language" },
  { label: "Light Language Activation", value: "Light Language Activation" },
  { label: "Lightfield", value: "Lightfield" },
  { label: "Longevity Coaching", value: "Longevity Coaching" },
  { label: "MAP Method", value: "MAP Method" },
  { label: "Magnetic Therapy", value: "Magnetic Therapy" },
  { label: "Manifestation", value: "Manifestation" },
  { label: "Marconics", value: "Marconics" },
  { label: "Martial Arts", value: "Martial Arts" },
  { label: "Massage Therapy", value: "Massage Therapy" },
  { label: "Matrix Energetics", value: "Matrix Energetics" },
  { label: "MediSounds", value: "MediSounds" },
  { label: "Medical Intuition", value: "Medical Intuition" },
  { label: "Medicine Wheel", value: "Medicine Wheel" },
  { label: "Meditation", value: "Meditation" },
  { label: "Meditation Coaching", value: "Meditation Coaching" },
  { label: "Menstrual Cycle Awareness", value: "Menstrual Cycle Awareness" },
  { label: "Mental Health Coaching", value: "Mental Health Coaching" },
  { label: "Mentoring", value: "Mentoring" },
  { label: "Metaphysical Counseling", value: "Metaphysical Counseling" },
  { label: "Mind Healing", value: "Mind Healing" },
  { label: "Mindfulness", value: "Mindfulness" },
  { label: "Music Therapy", value: "Music Therapy" },
  {
    label: "Native American Healing Practices",
    value: "Native American Healing Practices",
  },
  { label: "Naturopathic Medicine", value: "Naturopathic Medicine" },
  { label: "Neural Retraining", value: "Neural Retraining" },
  { label: "Neuro Emotional Technique", value: "Neuro Emotional Technique" },
  { label: "Neuro Meditation", value: "Neuro Meditation" },
  {
    label: "Neuro-linguistic Programming",
    value: "Neuro-linguistic Programming",
  },
  { label: "Neurofeedback", value: "Neurofeedback" },
  { label: "Neurosculpting", value: "Neurosculpting" },
  { label: "Nutrition Coaching", value: "Nutrition Coaching" },
  { label: "Nutritional Therapy", value: "Nutritional Therapy" },
  { label: "Occupational Therapy", value: "Occupational Therapy" },
  { label: "One Light Healing Touch", value: "One Light Healing Touch" },
  { label: "Oracle Reading", value: "Oracle Reading" },
  { label: "Osteomyology", value: "Osteomyology" },
  { label: "Osteopathy", value: "Osteopathy" },
  { label: "Other", value: "Other" },
  { label: "PSYCH-K", value: "PSYCH-K" },
  { label: "Past Life Regression", value: "Past Life Regression" },
  { label: "Pelvic Floor Therapy", value: "Pelvic Floor Therapy" },
  { label: "Physical Therapy", value: "Physical Therapy" },
  { label: "Pilates", value: "Pilates" },
  { label: "Polarity Therapy", value: "Polarity Therapy" },
  { label: "Polyvagal Theory Practices", value: "Polyvagal Theory Practices" },
  { label: "Postpartum Support", value: "Postpartum Support" },
  { label: "Pranic Healing", value: "Pranic Healing" },
  { label: "Prenatal Wellness", value: "Prenatal Wellness" },
  { label: "Prenatal Yoga", value: "Prenatal Yoga" },
  {
    label: "Progressive Muscle Relaxation",
    value: "Progressive Muscle Relaxation",
  },
  { label: "Psychic Healing", value: "Psychic Healing" },
  { label: "Psychopomp", value: "Psychopomp" },
  { label: "Psychotherapy", value: "Psychotherapy" },
  { label: "Qi Men Dun Jia", value: "Qi Men Dun Jia" },
  { label: "Qigong", value: "Qigong" },
  { label: "Quantum Healing", value: "Quantum Healing" },
  { label: "Quantum Touch", value: "Quantum Touch" },
  { label: "Radionics", value: "Radionics" },
  {
    label: "Rapid Transformational Therapy",
    value: "Rapid Transformational Therapy",
  },
  { label: "Recreational Therapy", value: "Recreational Therapy" },
  { label: "Reflexology", value: "Reflexology" },
  { label: "Reiki", value: "Reiki" },
  { label: "Relationship Coaching", value: "Relationship Coaching" },
  { label: "Restorative Yoga", value: "Restorative Yoga" },
  { label: "Rubenfeld Synergy", value: "Rubenfeld Synergy" },
  { label: "Salt Therapy", value: "Salt Therapy" },
  { label: "Self-hypnosis", value: "Self-hypnosis" },
  { label: "Sensory Healing", value: "Sensory Healing" },
  { label: "Shamanic Journeying", value: "Shamanic Journeying" },
  { label: "Shamanic Reiki", value: "Shamanic Reiki" },
  { label: "Shamanism", value: "Shamanism" },
  { label: "Shiatsu", value: "Shiatsu" },
  { label: "Siddha Medicine", value: "Siddha Medicine" },
  { label: "Sigils", value: "Sigils" },
  { label: "Somatic Therapy", value: "Somatic Therapy" },
  { label: "Sonopuncture", value: "Sonopuncture" },
  { label: "Soul Listening", value: "Soul Listening" },
  { label: "Soul Retrieval", value: "Soul Retrieval" },
  { label: "SoulCollage", value: "SoulCollage" },
  { label: "Sound Healing", value: "Sound Healing" },
  { label: "Sound Therapy", value: "Sound Therapy" },
  { label: "Spinal Flow Technique", value: "Spinal Flow Technique" },
  { label: "Spiritual Coaching", value: "Spiritual Coaching" },
  { label: "Spiritual Entrepreneurship", value: "Spiritual Entrepreneurship" },
  { label: "Spiritual Mind Treatment", value: "Spiritual Mind Treatment" },
  { label: "Spiritual Response Therapy", value: "Spiritual Response Therapy" },
  { label: "Spirituality", value: "Spirituality" },
  {
    label: "Systemic Family Constellation",
    value: "Systemic Family Constellation",
  },
  { label: "Tai Chi", value: "Tai Chi" },
  { label: "Tantra", value: "Tantra" },
  { label: "Tantric Yoga", value: "Tantric Yoga" },
  { label: "Tarot Reading", value: "Tarot Reading" },
  { label: "Thai Bodywork", value: "Thai Bodywork" },
  { label: "Thai Massage", value: "Thai Massage" },
  { label: "Therapeutic Touch", value: "Therapeutic Touch" },
  { label: "Theta Healing", value: "Theta Healing" },
  { label: "Thought Field Therapy", value: "Thought Field Therapy" },
  { label: "Tibetan Singing Bowls", value: "Tibetan Singing Bowls" },
  {
    label: "Traditional Chinese Medicine",
    value: "Traditional Chinese Medicine",
  },
  {
    label: "Traditional Japanese Medicine",
    value: "Traditional Japanese Medicine",
  },
  {
    label: "Traditional Korean Medicine",
    value: "Traditional Korean Medicine",
  },
  {
    label: "Traditional Mongolian Medicine",
    value: "Traditional Mongolian Medicine",
  },
  {
    label: "Traditional Tibetan Medicine",
    value: "Traditional Tibetan Medicine",
  },
  { label: "Trance Healing", value: "Trance Healing" },
  { label: "Transcendental Meditation", value: "Transcendental Meditation" },
  { label: "Transformational Coaching", value: "Transformational Coaching" },
  { label: "Trauma-Informed Yoga", value: "Trauma-Informed Yoga" },
  { label: "Tuina", value: "Tuina" },
  { label: "Tuning Forks", value: "Tuning Forks" },
  { label: "Vibrational Therapy", value: "Vibrational Therapy" },
  { label: "Vinyasa Yoga", value: "Vinyasa Yoga" },
  { label: "Vipassana", value: "Vipassana" },
  { label: "Visualization", value: "Visualization" },
  { label: "Vocal Activation", value: "Vocal Activation" },
  { label: "Vocal Toning", value: "Vocal Toning" },
  { label: "Voice Healing Therapy", value: "Voice Healing Therapy" },
  { label: "Voice Therapy", value: "Voice Therapy" },
  { label: "Wellness Coaching", value: "Wellness Coaching" },
  { label: "Women's Health Coaching", value: "Women's Health Coaching" },
  { label: "Yagerian Therapy", value: "Yagerian Therapy" },
  { label: "Yin Yoga", value: "Yin Yoga" },
  { label: "Yoga", value: "Yoga" },
  { label: "Yoga Therapy", value: "Yoga Therapy" },
  { label: "Zang Fu Theory", value: "Zang Fu Theory" },
  { label: "Zenthai Shiatsu Therapy", value: "Zenthai Shiatsu Therapy" },
  { label: "Other", value: "Other" },
];

export const tagsOptions = [
  "Stress relief",
  "Emotional healing",
  "Creativity",
  "Self Discovery",
  "Women's wellness",
  "Spiritual growth",
  "Sleep improvement",
  "Inner child healing",
  "Energy balancing",
  "Physical recovery",
  "Detox",
  "Men's wellness",
  "Grief support",
  "Chakra balancing",
  "Burnout recovery",
];

export const accessibilityItem = [
  "Wheelchair accessible",
  "Quiet environment",
  "Guide dog allowed",
  "Reserved parking for disabled",
  "Visual support available",
  "Braille materials",
  "Hearing support",
  "Accessible toilets",
  "Sign language interpreter",
  "High readability materials",
  "Cognitive support",
  "Elevator available",
  "Other",
];

export const eventItem = [
  {
    value: "onetoone",
    label: "1:1",
  },
  {
    value: "group",
    label: "Group",
  },
  {
    value: "retreat",
    label: "Retreat",
  },
];

export const delivaryOptions = [
  { value: "offline", label: "Offline", icon: "offline" },
  { value: "online", label: "Online", icon: "online" },
  { value: "ondemand", label: "On demand", icon: "ondemand" },
];

export const purposeItem = [
  { value: "educational", label: "Educational" },
  { value: "experimental", label: "Experiential" },
  { value: "mixed", label: "Mixed" },
];

export const durationOptions = [
  { value: "less_than_30_minutes", label: "Less than 30 minutes" },
  { value: "30_60_minutes", label: "30-60 minutes" },
  { value: "1_2_hours", label: "1-2 hours" },
  { value: "half_day", label: "Half day" },
  { value: "one_day", label: "One day" },
  { value: "two_days", label: "Two days" },
  { value: "three_days", label: "Three days" },
  { value: "four_days", label: "Four days" },
  { value: "five_days", label: "Five days" },
  { value: "one_week", label: "One week" },
  { value: "more_than_one_week", label: "More than one week" },
];

// country options
export const countryOptions = [
  { label: "Italy", value: "Italy" },
  { label: "USA", value: "America" },
];

export const regionOptions = [
  { label: "Lazio", value: "Lazio" },
  { label: "Tuscany", value: "Tuscany" },
  { label: "California", value: "California" },
  { label: "Texas", value: "Texas" },
];

export const genderOptions = [
  { label: "Male", value: "male" },
  { label: "Female", value: "female" },
  { label: "Others", value: "others" },
];

export const provinceOptions = [
  { label: "Lazio", value: "Lazio" },
  { label: "Tuscany", value: "Tuscany" },
  { label: "New York", value: "New York" },
  { label: "Florida", value: "Florida" },
];

export const cityOptions = [
  { label: "Rome", value: "Rome" },
  { label: "Milan", value: "Milan" },
  { label: "Florence", value: "Florence" },
  { label: "Venice", value: "Venice" },
  { label: "Los Angeles", value: "Los Angeles" },
  { label: "New York City", value: "New York" },
  { label: "Chicago", value: "Chicago" },
  { label: "San Francisco", value: "San Francisco" },
];

export const dateOption = [
  { label: "Today", value: "today" },
  { label: "Tomorrow", value: "tomorrow" },
  { label: "This Month", value: "this_month" },
  { label: "Next Month", value: "next_month" },
];

export const newsLetterOption = [
  {
    label: "User Purchase",
    value: newsletSts.userPurchase,
  },
  {
    label: "Operator Sales",
    value: newsletSts.operatorSales,
  },
  {
    label: "User Metrics",
    value: newsletSts.userMetrics,
  },
  {
    label: "Operator Metrics",
    value: newsletSts.operatorMetrics,
  },
  {
    label: "User Disciplines",
    value: newsletSts.userDisciplines,
  },
  {
    label: "Operator Disciplines",
    value: newsletSts.operatorDisciplines,
  },
  {
    label: "User Event",
    value: newsletSts.userEvent,
  },
  {
    label: "Operator Event",
    value: newsletSts.operatorEvent,
  },
  {
    label: "Purpose",
    value: newsletSts.purpose,
  },
  {
    label: "Tags",
    value: newsletSts.tags,
  },
  {
    label: "Locations",
    value: newsletSts.locations,
  },
  {
    label: "Duration",
    value: newsletSts.duration,
  },
  {
    label: "Price",
    value: newsletSts.price,
  },
  {
    label: "Capacity",
    value: newsletSts.capacity,
  },
  {
    label: "Accessibility",
    value: newsletSts.accessibility,
  },
  {
    label: "Subscribed",
    value: newsletSts.subscribed,
  },
];
